name: Cron Health
on:
  schedule:
    - cron: "*/10 * * * *"   # every 10 minutes
  workflow_dispatch:
env:
  API: https://hbuk-backend-hvow.onrender.com
jobs:
  health:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      # No npm ci needed
      - name: Healthcheck
        run: node scripts/healthcheck.mjs
